version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    # login to Elastic container registry
    - eval $(aws ecr get-login --region ap-southeast-1 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=882337585157.dkr.ecr.ap-southeast-1.amazonaws.com/kyc/web
    - IMAGE_TAG=latest
  build:
    commands:
    - echo Build started on `date`
    - echo installing dependencies..
    - npm install
    - echo Building the Docker image...
    - docker login --username vincedilig --password GuerillaThree60!
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - aws ecs update-service --cluster KYC-Prod --service kyc-web-prod --force-new-deployment
